### PR TITLE
A Module for Humours

### PR DESCRIPTION
**Pull request by DeepwaterCreations**
I might want to use this for the next game I run. It tracks the body's four humours.
I'll reveal what the heck that actually means in due course.

### CODE REVIEW

**Comment by os-nicolas** [comment]
DC, this looks great!

One thing: I have been trying to have three part ids (x-y-z). Similar to domain names or java packages. Would you mind updating your id to follow this convention?

I am not *that* attached to this convention, it might be totally unnecessary.  I could pretty easily be talked in to dropping it.

**Comment by DeepwaterCreations** [comment]
Sure, no prob.

**Comment by DeepwaterCreations** [comment]
FWIW, I don't know if "tote-hughes" or "colin-wielga" really contains any more information than "totehughes" or "colinwielga," though. Seems to me your first and last names are parts of the same category/level of specificity.
I think I'll go with "dc-humours-sliders" so I can do "dc-humours-cards" etc. later on.

**Comment by DeepwaterCreations** [comment]
Also, if I expanded "dc" then I would lose that lovely ambiguity over whether it's "dylan craine" or "deepwater creations".

**Comment by DeepwaterCreations** [comment]
Done.

**Comment by os-nicolas** [comment]
I agree on all points. I do love that ambiguity.

**Pull request merged**
